// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsJXdfGQqwdHnBcp8xMCO6HeeueB6tj4',
    appId: '1:533213828413:web:57868a70c0575ab5ba2154',
    messagingSenderId: '533213828413',
    projectId: 'latihanutspab2-30d6f',
    authDomain: 'latihanutspab2-30d6f.firebaseapp.com',
    databaseURL: 'https://latihanutspab2-30d6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanutspab2-30d6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0DatYfCpDRhiyja2ciKh9YfsskXWEzD8',
    appId: '1:533213828413:android:e43eaef88054c16fba2154',
    messagingSenderId: '533213828413',
    projectId: 'latihanutspab2-30d6f',
    databaseURL: 'https://latihanutspab2-30d6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanutspab2-30d6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjKPoVXff1qdLVbldIpr-6QIfoicj4vz0',
    appId: '1:533213828413:ios:a23f9c5460bef2bbba2154',
    messagingSenderId: '533213828413',
    projectId: 'latihanutspab2-30d6f',
    databaseURL: 'https://latihanutspab2-30d6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanutspab2-30d6f.firebasestorage.app',
    iosBundleId: 'com.example.latihanutspab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjKPoVXff1qdLVbldIpr-6QIfoicj4vz0',
    appId: '1:533213828413:ios:a23f9c5460bef2bbba2154',
    messagingSenderId: '533213828413',
    projectId: 'latihanutspab2-30d6f',
    databaseURL: 'https://latihanutspab2-30d6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanutspab2-30d6f.firebasestorage.app',
    iosBundleId: 'com.example.latihanutspab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqsJXdfGQqwdHnBcp8xMCO6HeeueB6tj4',
    appId: '1:533213828413:web:c51a80184d8acae8ba2154',
    messagingSenderId: '533213828413',
    projectId: 'latihanutspab2-30d6f',
    authDomain: 'latihanutspab2-30d6f.firebaseapp.com',
    databaseURL: 'https://latihanutspab2-30d6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihanutspab2-30d6f.firebasestorage.app',
  );

}